Task 2
enginire4ek/Pinterbest pull request #2
Opened 2021-11-06 11:40 UTC by enginire4ek

- Added a feed of pins on the Home page
- Home page wrapped in SwipeRefreshLayout
- Removed @SuppressLint("RestrictedApi") note when navigating BackStack
- Changed adapter class
- In some XML files, the language of the help information has been changed to Russian

2021-11-08 13:41 UTC, 102Rudy requested changes

2021-11-08 13:41 UTC, 102Rudy commented on app/src/main/java/com/example/pinterbest/HomeFragment.kt
> +        }
it's better to use `GONE` instead of `INVISIBLE`

2021-11-08 13:41 UTC, 102Rudy commented on app/src/main/java/com/example/pinterbest/adapters/PinFeedHomeAdapter.kt
> +    private var pinObjects: PinsFeed = PinsFeed(listOf())
PinsFeed must not be used in UI logic because it is Business model. Consider creating Model especially for using on UI

2021-11-08 13:41 UTC, 102Rudy commented on app/src/main/java/com/example/pinterbest/viewmodels/HomeViewModel.kt
> +    AndroidViewModel(application) {
Why do you use `AndroidViewModel` instead of the base one? (I don't remember the name)
Looks like you can use default ViewModel

2021-11-09 09:24 UTC, enginire4ek commented on app/src/main/java/com/example/pinterbest/HomeFragment.kt
> +        }
Fixed here https://github.com/enginire4ek/Pinterbest/pull/2/commits/d8b9e4e644b216cf3291efa52158f7106e897b56

2021-11-09 09:24 UTC, enginire4ek commented on app/src/main/java/com/example/pinterbest/adapters/PinFeedHomeAdapter.kt
> +    private var pinObjects: PinsFeed = PinsFeed(listOf())
Fixed here https://github.com/enginire4ek/Pinterbest/pull/2/commits/d8b9e4e644b216cf3291efa52158f7106e897b56

2021-11-09 09:24 UTC, enginire4ek commented on app/src/main/java/com/example/pinterbest/viewmodels/HomeViewModel.kt
> +    AndroidViewModel(application) {
Fixed here https://github.com/enginire4ek/Pinterbest/pull/2/commits/d8b9e4e644b216cf3291efa52158f7106e897b56

2021-11-10 17:03 UTC, 102Rudy approved these changes

2021-11-10 17:03 UTC, 102Rudy commented on app/src/main/java/com/example/pinterbest/api/ApiClient.kt
> +        }
this implementation is not thread-safe

2021-11-10 17:03 UTC, 102Rudy commented on app/src/main/java/com/example/pinterbest/adapters/PinObjectViewData.kt
> +}
Discussed, it's mixing of domains

2021-11-10 18:10 UTC, merged